# Default configuration file is $HOME/.config/vlto.toml

# Your api token can be found in https://toggl.com/app/profile
ApiToken = "0123456789abcdefghijklmnopqrstuv"

# A workspace which has time entries of your projects
WorkSpaceId = "1234567"


# Settings of each project
[[Projects]]

# Project name defined in Toggl
Name = "Sample Project 1"

# Working hours you try to achieve
TargetHour = 1000

# A date when aggregation of time entries starts
# Time and timezone are necessary even though they aren't used by application
StartDate = 2016-10-11T00:00:00+00:00

# Number of days in 1 iteration
IterationDays = 7

[[Projects]]
Name = "Sample Project 2"
TargetHour = 2000
StartDate = 2019-01-01T00:00:00+00:00
IterationDays = 14