# Default configuration file is $HOME/.config/vlto.toml

# Your api token can be found in https://toggl.com/app/profile
APIToken = "1971800d4d82861d8f2c1651fea4d212"

# A workspace which has time entries of your projects
WorkSpaceID = "1234567"


# Each project settings
[[Projects]]

# Project name defined in Toggl
Name = "Sample Project 1"

# Working hours you try to achieve
Goal = 1000

# A date when aggregation of time entries starts
# Time and timezone are necessary even though they aren't used by application
StartDate = 2016-10-11T00:00:00+00:00

# Number of weeks in 1 iteration
Iteration = 1

[[Projects]]
Name = "Sample Project 2"
Goal = 2000
StartDate = 2019-01-01T00:00:00+00:00
Iteration = 2